# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-09-16 14:25
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('df_cart', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cartinfo',
            old_name='ctoun',
            new_name='count',
        ),
    ]
